@base = http://localhost:3000

### Check status
GET {{base}}/status

### Get all articles
GET {{base}}/articles

### Get hello-world article
GET {{base}}/articles/hello-world

### Add new article
POST {{base}}/articles
Content-Type: application/json

{
  "title": "New article",
  "slug": "new-article",
  "body": "This is a new article",
  "heroImage": "https://example.com/image.jpg",
  "tags": "[\"new\", \"article\"]"	
}