services:
  devcontainer: 
    image: mcr.microsoft.com/devcontainers/rust:latest
    volumes:
      - ..:/workspace:cachec
    command: sleep infinity
    env_file:
      - .env

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    env_file:
      - .env